---
version: '3'

services:
  app:
    image: jchouhan19/1stimage
    #  build: ./app
    ports:
      - 8000:8000
    depends_on:
      - db
  web:
    build: ./web
    ports:
      - 8080:80
    depends_on:
      - app
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: backenddb
      MYSQL_USER: backend
      MYSQL_PASSWORD: securepass
    ports: 
      - 3306:3306

  insert:
    build: ./insert
    env_file: ./variables.env
    depends_on:
      - app
      - web

     
